### ISSUE TITLE
Enabled use it with any mailing provider

### ISSUE THREAD

**Issue by SalahAdDin** [luluhoc/medusa-plugin-abandoned-cart#11]
Hello there,

This plugin is heavily tied to the Sendgrid Mail service, but not all people either use it or can pay for it.

Would it be hard to adapt this plugin to use the preferred mailing provider plugin/service?

**Comment by luluhoc** [comment]
@SalahAdDin Let me look into it

**Comment by luluhoc** [comment]
@SalahAdDin Check the 1.2.0 and new readme the plugin now emits the event so you can handle yourself sending emails.

**Comment by SalahAdDin** [comment]
@luluhoc could you provide any example? 

Thank you

**Comment by luluhoc** [comment]
@SalahAdDin I have added an example

**Comment by SalahAdDin** [comment]
@luluhoc [this one,](https://github.com/luluhoc/medusa-plugin-abandoned-cart/commit/08318b2fab26908a68581d4532657c70eb457097) right? but it works with Sendgrid, what about another one that does not use Sendgrid? like SMP or Node Mailer?

**Comment by luluhoc** [comment]
Yes, this one, I made an example with Sendgrid but based on my example you can use any notification provider.
