### ISSUE TITLE
Feature Request: Add automated emails with a configurable schedule

### ISSUE THREAD

**Issue by DoubleOTheven** [luluhoc/medusa-plugin-abandoned-cart#12]
This is a great plugin. It would be nice if we could set a schedule to trigger the emails automatically and space out the time they are sent.

e.g. In the Medusa Config we can set: `[1 hr, 1 day, 5 days]`. Then a cron job looks for abandoned carts and sends the email 1 hour after the cart has been abandoned. Then it will send another email 1 day after the cart was abandoned. Then finally it will send the email 5 days after it has been abandoned. After this no more emails will be sent.

**Comment by luluhoc** [comment]
@DoubleOTheven Cool idea, I was meant to do something similar, I will try to push the commit today ;)

**Comment by luluhoc** [comment]
check @DoubleOTheven  2.0.0
