### ISSUE TITLE
Abandoned Carts Name shows undefined

### ISSUE THREAD

**Issue by krisrego** [luluhoc/medusa-plugin-abandoned-cart#19]
For some reason for the medusa admin panel am getting undefined for first name and last name even if the user has entered his/her name during registration

<img width="1165" alt="Screenshot 2024-05-17 at 2 09 42 PM" src="https://github.com/luluhoc/medusa-plugin-abandoned-cart/assets/134923624/ac119913-545d-4966-bb72-ae38e8d00c47">

I have installed the medusa-plugin-abandoned-cart and followed the instructions everything seems to work fine but the first name and last name seems to show undefined

**Comment by luluhoc** [comment]
@krisrego Can you give me the version you are on and, the data that is received from the API via DEVTOOLS?

Ideally, also the mentioned cart with shipping-address relation?

**Comment by krisrego** [comment]
Add to restart the system for some reason works fine
